### PR TITLE
"Use Incense" from inventory menu

### PR DESCRIPTION
**Pull request by tsnork**

### CODE REVIEW

**Comment by Lunat1q** [comment]
sorry, that's pretty raw code, i can't accept it:
1. There was usage of Incense at the inventory manager, line 109
2. You need to do a lot of UI stuff, like the option to SHOW what u used Incense somewhere at UI
3. PREVENT using Incense from the UI if old one is still active
4. Detect active incense EVEN bot was reloaded/restarted
5. Take a look at Catch Incense pokemon task, and ensure what it see Incense usage.

**Comment by Lunat1q** [comment]
i was planning to do all that by myself during this week, but if u started, do u want to finish it?

**Comment by tsnork** [comment]
Hi,

yeah - I confess, I just did it in a matter of minutes because I wanted to be able to use incense and didn't care about sloppyness.

I can try to do this in a cleaner way, but I have not done very much in c#, I'm more of a web developer, so it might take some time.

**Comment by Waltii** [comment]
Hello, can you add a feature to use manually lucky egg by the bot please? 
The automatic function does not work. I did not forget to check "Use lucky eggs while evolving" and "lucky eggs min poke to 50.

**Comment by Peteleko** [comment]
Hello , How do I Translation Program for Brazilian Portuguese ?

**Comment by jaddad07** [comment]
is this feature coming soon?, I like the idea of having options to use incense and maybe hang out (paused) at a pokestop with a lure as well.  wish I was a programmer, I am old that writing perl scripts was my gig back in the day for making awesome webpages on the fly....

**Pull request closed without merging**
