### PR TITLE
Find nearest point

### PR DESCRIPTION
**Pull request by kchen-tw**
When use GPX file, always find nearest point to start walk.

### CODE REVIEW

**Comment by misakiw** [comment]
Hi kchen-tw , 

Suggest to change the existing translation zh_tw to zh_hk (for Hong Kong) before applying your fix.

**Comment by Lunat1q** [comment]
GPX is obsolute, will be replaced soon
Also nearest trackpoint can be not the next one, you may have complex routes.

**Comment by Lunat1q** [comment]
I agree to accept translation changes, but not the GPX one.

**Comment by Alicesaglisse33** [comment]
Hello, my bot do not use the human pathing even if it's checked. Do you have a solution ?
(The bot fly over the buildings travelling from a pokestop to an other pokestop, not using the street like an human)
Thanks.
(Sorry for my english, i'm french..)

**Comment by kchen-tw** [comment]
Hi @Alicesaglisse33  
1. You can visitethe website https://wtracks.appspot.com/ 
2. Create the track point by youself.
3. When you finish your track path, you can save to the  `*.GPX` file with select` Don't save metadata`
4. Save `*.GPX `on  `Catchem.exe` same folder
5.Open your profiles `config.json`, 
  * modify `"UseGpxPathing": false,` to `"UseGpxPathing": true,` , and 
  * modify `"GpxFile": "GPXFile.GPX"`, to `"GpxFile": "YourFIle.GPX"`,
Good luck

**Pull request closed without merging**
