### PR TITLE
Incense 3.1

### PR DESCRIPTION
**Pull request by tsnork**
Bah, wanted to do the PR to dev, sorry.

### CODE REVIEW

**Comment by Lunat1q** [comment]
19 files changed?:)

**Comment by tsnork** [comment]
Yup, to reduce api calls while catching on the move I changed some files to only use the Incense-Task when Incense is active and so on.

**Comment by Vinicuis** [comment]
How do I use these codes?

**Comment by tsnork** [comment]
Either you compile yourself from my branch or you wait until luna might merge this.

**Comment by Lunat1q** [comment]
Sorry mate, this PR is a bit "messed" can't accept it :/
Also it's a bit non-generic solution, which need to be rewritten from scratch :/

**Pull request closed without merging**
